version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-fpm
    networks:
      - nginx-php82-fpm

  php82-fpm:
    container_name: php82-fpm-container
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
        - ./app:/var/www/project
    networks:
      - nginx-php82-fpm
networks:
  nginx-php82-fpm: